# Generated by Django 6.1.1 on 2026-09-18 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_name', models.CharField(max_length=255)),
                ('resume_text', models.TextField()),
                ('score', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('detected_skills', models.TextField()),
                ('job_skills', models.TextField()),
                ('matched_skills', models.TextField()),
                ('missing_skills', models.TextField()),
                ('match_percentage', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
