# Generated by Django 6.1.1 on 2026-09-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='category',
            field=models.CharField(default='General IT', max_length=100),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='detected_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='job_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='match_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='matched_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='missing_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
