# Generated by Django 6.1.1 on 2026-09-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_resumeanalysis_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='job_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
